### ISSUE TITLE
AttributeError: module 'os' has no attribute 'cls'

### ISSUE THREAD

**Issue by Euan-Hall** [Euan-Hall/RPG-TextBased#2]
Traceback (most recent call last):
  File "Z:/PyRPG/Main.py", line 43, in <module>
    menu()
  File "Z:/PyRPG/Main.py", line 29, in menu
    os.cls()
AttributeError: module 'os' has no attribute 'cls'

**Comment by Euan-Hall** [comment]
Changed os.cls() to os.system('cls')
